// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7TxOp48uAIVUevy6YIrhfmqCynRmXApE',
    appId: '1:345436780940:web:0490935c98bb35436dfea9',
    messagingSenderId: '345436780940',
    projectId: 'tracelet-app',
    authDomain: 'tracelet-app.firebaseapp.com',
    storageBucket: 'tracelet-app.firebasestorage.app',
    measurementId: 'G-WCRY9VMVFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf7oinnidr0pcI0AB2034WmRqSYXTMeNk',
    appId: '1:345436780940:android:3285034e9cd167416dfea9',
    messagingSenderId: '345436780940',
    projectId: 'tracelet-app',
    storageBucket: 'tracelet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvPabbtdfMOnQjS3WnnwtRpMmpNZ2uNyA',
    appId: '1:345436780940:ios:8730f41a4c41cb826dfea9',
    messagingSenderId: '345436780940',
    projectId: 'tracelet-app',
    storageBucket: 'tracelet-app.firebasestorage.app',
    iosBundleId: 'com.example.traceletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvPabbtdfMOnQjS3WnnwtRpMmpNZ2uNyA',
    appId: '1:345436780940:ios:8730f41a4c41cb826dfea9',
    messagingSenderId: '345436780940',
    projectId: 'tracelet-app',
    storageBucket: 'tracelet-app.firebasestorage.app',
    iosBundleId: 'com.example.traceletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7TxOp48uAIVUevy6YIrhfmqCynRmXApE',
    appId: '1:345436780940:web:abf157c674038d566dfea9',
    messagingSenderId: '345436780940',
    projectId: 'tracelet-app',
    authDomain: 'tracelet-app.firebaseapp.com',
    storageBucket: 'tracelet-app.firebasestorage.app',
    measurementId: 'G-W01VP9V7VL',
  );
}
